---
abstract: 'FrameWork Sites version 2 socketlabs.com SMTP integration'
author:
  - 'Nate Lewis <nlewis@gnetworks.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FWS-V2-SocketLabs
no_index:
  directory:
    - t
    - inc
requires:
  Authen::SASL: 0
  MIME::Base64: 0
  MIME::Lite: 0
  Test::More: 0
version: 0.01
